"""add emergency mode

Revision ID: 08024a67b882
Revises: 4cc6ef12f975
Create Date: 2026-09-16 15:14:10.203089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08024a67b882'
down_revision: Union[str, Sequence[str], None] = '4cc6ef12f975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nations', sa.Column('is_emergency_mode', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nations', 'is_emergency_mode')
    # ### end Alembic commands ###
