"""add_medicine_forecasts

Revision ID: 27f8d9069dd1
Revises: f20e57630418
Create Date: 2026-09-16 15:01:18.948532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27f8d9069dd1'
down_revision: Union[str, Sequence[str], None] = 'f20e57630418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine_forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('projected_stockout_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['health_centres.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medicine_forecasts_hospital_id'), 'medicine_forecasts', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_medicine_forecasts_id'), 'medicine_forecasts', ['id'], unique=False)
    op.create_index(op.f('ix_medicine_forecasts_item_id'), 'medicine_forecasts', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medicine_forecasts_item_id'), table_name='medicine_forecasts')
    op.drop_index(op.f('ix_medicine_forecasts_id'), table_name='medicine_forecasts')
    op.drop_index(op.f('ix_medicine_forecasts_hospital_id'), table_name='medicine_forecasts')
    op.drop_table('medicine_forecasts')
    # ### end Alembic commands ###
