"""Add nation_id to HealthCentre and User

Revision ID: 46fb6a159b19
Revises: 08024a67b882
Create Date: 2026-09-16 17:26:53.830173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46fb6a159b19'
down_revision: Union[str, Sequence[str], None] = '08024a67b882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_centres', sa.Column('nation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_health_centres_nation_id'), 'health_centres', ['nation_id'], unique=False)
    op.create_foreign_key(None, 'health_centres', 'nations', ['nation_id'], ['id'])
    op.add_column('users', sa.Column('nation_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_nation_id'), 'users', ['nation_id'], unique=False)
    op.create_foreign_key(None, 'users', 'nations', ['nation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_nation_id'), table_name='users')
    op.drop_column('users', 'nation_id')
    op.drop_constraint(None, 'health_centres', type_='foreignkey')
    op.drop_index(op.f('ix_health_centres_nation_id'), table_name='health_centres')
    op.drop_column('health_centres', 'nation_id')
    # ### end Alembic commands ###
