"""add federated model version

Revision ID: 4cc6ef12f975
Revises: 27f8d9069dd1
Create Date: 2026-09-16 15:08:09.726522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc6ef12f975'
down_revision: Union[str, Sequence[str], None] = '27f8d9069dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federated_model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('local_coef', sa.String(), nullable=True),
    sa.Column('local_intercept', sa.Float(), nullable=True),
    sa.Column('local_mae', sa.Float(), nullable=True),
    sa.Column('global_coef', sa.String(), nullable=True),
    sa.Column('global_intercept', sa.Float(), nullable=True),
    sa.Column('global_mae', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_federated_model_versions_category'), 'federated_model_versions', ['category'], unique=False)
    op.create_index(op.f('ix_federated_model_versions_id'), 'federated_model_versions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_federated_model_versions_id'), table_name='federated_model_versions')
    op.drop_index(op.f('ix_federated_model_versions_category'), table_name='federated_model_versions')
    op.drop_table('federated_model_versions')
    # ### end Alembic commands ###
