"""Add donor_phc_id to ResourceRequest

Revision ID: 5253f267fdb6
Revises: 81d7cfeefaf2
Create Date: 2026-09-17 03:13:11.656448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5253f267fdb6'
down_revision: Union[str, Sequence[str], None] = '81d7cfeefaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_requests', sa.Column('donor_phc_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resource_requests_donor_phc_id'), 'resource_requests', ['donor_phc_id'], unique=False)
    op.create_foreign_key(None, 'resource_requests', 'health_centres', ['donor_phc_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_requests', type_='foreignkey')
    op.drop_index(op.f('ix_resource_requests_donor_phc_id'), table_name='resource_requests')
    op.drop_column('resource_requests', 'donor_phc_id')
    # ### end Alembic commands ###
