"""Add Aggregator Models

Revision ID: 81d7cfeefaf2
Revises: 46fb6a159b19
Create Date: 2026-09-17 02:46:12.571561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81d7cfeefaf2'
down_revision: Union[str, Sequence[str], None] = '46fb6a159b19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregator_global_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('coef', sa.String(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregator_global_models_category'), 'aggregator_global_models', ['category'], unique=True)
    op.create_index(op.f('ix_aggregator_global_models_id'), 'aggregator_global_models', ['id'], unique=False)
    op.create_table('aggregator_local_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=False),
    sa.Column('nation_name', sa.String(), nullable=False),
    sa.Column('phc_name', sa.String(), nullable=False),
    sa.Column('coef', sa.String(), nullable=False),
    sa.Column('intercept', sa.Float(), nullable=False),
    sa.Column('mae', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregator_local_updates_category'), 'aggregator_local_updates', ['category'], unique=False)
    op.create_index(op.f('ix_aggregator_local_updates_id'), 'aggregator_local_updates', ['id'], unique=False)
    op.create_index(op.f('ix_aggregator_local_updates_nation_id'), 'aggregator_local_updates', ['nation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aggregator_local_updates_nation_id'), table_name='aggregator_local_updates')
    op.drop_index(op.f('ix_aggregator_local_updates_id'), table_name='aggregator_local_updates')
    op.drop_index(op.f('ix_aggregator_local_updates_category'), table_name='aggregator_local_updates')
    op.drop_table('aggregator_local_updates')
    op.drop_index(op.f('ix_aggregator_global_models_id'), table_name='aggregator_global_models')
    op.drop_index(op.f('ix_aggregator_global_models_category'), table_name='aggregator_global_models')
    op.drop_table('aggregator_global_models')
    # ### end Alembic commands ###
