"""add_nation_tier

Revision ID: f20e57630418
Revises: 8c4d2d7cc1fa
Create Date: 2026-09-16 14:53:45.606755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f20e57630418'
down_revision: Union[str, Sequence[str], None] = '8c4d2d7cc1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('data_residency_region', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nations_id'), 'nations', ['id'], unique=False)
    op.create_index(op.f('ix_nations_iso_code'), 'nations', ['iso_code'], unique=True)
    op.create_index(op.f('ix_nations_name'), 'nations', ['name'], unique=True)
    op.create_table('districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('nation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nation_id'], ['nations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_districts_id'), 'districts', ['id'], unique=False)
    op.create_index(op.f('ix_districts_name'), 'districts', ['name'], unique=False)
    op.create_index(op.f('ix_attendance_records_user_id'), 'attendance_records', ['user_id'], unique=False)

    # --- Add Data Migration ---
    # 0. Add NATION_ADMIN to enum type
    connection = op.get_bind()
    # Check if 'NATION_ADMIN' exists in enum, if not, add it
    connection.execute(sa.text("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'NATION_ADMIN'"))
    connection.commit()

    # 1. Insert "India" into nations
    nations_table = sa.table('nations',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String),
        sa.column('iso_code', sa.String),
        sa.column('data_residency_region', sa.String),
        sa.column('created_at', sa.DateTime)
    )
    
    op.bulk_insert(nations_table,
        [
            {'id': 1, 'name': 'India', 'iso_code': 'IND', 'data_residency_region': 'ap-south-1'}
        ]
    )

    # 2. Extract existing districts from health_centres and insert into districts
    connection = op.get_bind()
    health_centres = connection.execute(sa.text("SELECT DISTINCT district, state FROM health_centres")).fetchall()
    
    if health_centres:
        districts_table = sa.table('districts',
            sa.column('name', sa.String),
            sa.column('state', sa.String),
            sa.column('nation_id', sa.Integer)
        )
        
        district_data = [
            {'name': hc[0], 'state': hc[1], 'nation_id': 1}
            for hc in health_centres if hc[0] and hc[1]
        ]
        
        if district_data:
            op.bulk_insert(districts_table, district_data)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_records_user_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_districts_nation_id'), table_name='districts')
    op.drop_index(op.f('ix_districts_name'), table_name='districts')
    op.drop_index(op.f('ix_districts_id'), table_name='districts')
    op.drop_table('districts')
    op.drop_index(op.f('ix_nations_name'), table_name='nations')
    op.drop_index(op.f('ix_nations_iso_code'), table_name='nations')
    op.drop_index(op.f('ix_nations_id'), table_name='nations')
    op.drop_table('nations')
    # ### end Alembic commands ###
